// export const FETCH_POSTS = "FETCH_POSTS";
// export const SET_LOADING = "SET_LOADING";

export const SET_USERTOKEN_FROM_LOGIN = "SET_USERTOKEN_FROM_LOGIN";
export const SET_USERTOKEN_FROM_REGISTER = "SET_USERTOKEN_FROM_REGISTER";