export const SET_USERTOKEN_FROM_REGISTER = "SET_USERTOKEN_FROM_REGISTER";

export const SET_LOGIN = "SET_LOGIN";
export const SET_USER_FROM_TOKEN = "SET_USER_FROM_TOKEN";

export const SET_ERROR = "SET_ERROR";
export const SET_NOT_ERROR = "SET_NOT_ERROR";
