export const SET_LOADING_NEW = "SET_LOADING_NEW";
export const GET_NEW_CAMPAIGNS = "GET_NEW_CAMPAIGNS";

export const SET_LOADING_TRENDING = "SET_LOADING_TRENDING";
export const GET_TRENDING_CAMPAIGN = "GET_TRENDING_CAMPAIGN";

export const SET_LOADING_POPULAR = "SET_LOADING_POPULAR";
export const GET_POPULAR_CAMPAIGNS = "GET_POPULAR_CAMPAIGNS";

export const SET_LOADING_URGENT = "SET_LOADING_URGENT";
export const GET_URGENT_CAMPAIGNS = "GET_URGENT_CAMPAIGNS";

export const SET_LOADING_CATEGORY = "SET_LOADING_CATEGORY";
export const GET_CATEGORY_CAMPAIGNS = "GET_CATEGORY_CAMPAIGNS";

export const SET_LOADING_SEARCH = "SET_LOADING_SEARCH";
export const GET_SEARCH_CAMPAIGNS = "GET_SEARCH_CAMPAIGNS";
export const GET_SEARCH_POPULAR = "GET_SEARCH_POPULAR";
export const GET_SEARCH_URGENT = "GET_SEARCH_URGENT";
export const GET_SEARCH_LESSDONATE = "GET_SEARCH_LESSDONATE";
